### ISSUE TITLE
an error when I try to update the singular

### ISSUE THREAD

**Issue by AmplitudeGravity** [wbhart/Singular.jl#50]
pkg> dev --local https://github.com/oscar-system/Singular.jl
    Cloning git-repo `https://github.com/oscar-system/Singular.jl`
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CxxWrap [1f15a43c]:
 CxxWrap [1f15a43c] log:
 ├─possible versions are: [0.1.0-0.1.8, 0.2.0-0.2.3, 0.3.0-0.3.1, 0.4.0-0.4.1, 0.5.0, 0.6.0-0.6.1, 0.7.0-0.7.4, 0.8.0-0.8.2] or uninstalled
 └─restricted to versions 0.10.1-0.10 by Singular [bcd08a7b] — no versions left
   └─Singular [bcd08a7b] log:
     ├─possible versions are: 0.3.0 or uninstalled
     └─Singular [bcd08a7b] is fixed to version 0.3.0

**Comment by wbhart** [comment]
Hi, the official Singular.jl repository is here:

https://github.com/oscar-system/Singular.jl

You should report problems there.

But if you want to develop Singular.jl (which is what dev is for), you need to keep the packages up-to-date yourself. Julia can't do it for you because it doesn't touch dev directories.
